CREATE TABLE LUNS_PROJECT (
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(512) NOT NULL,
    "DESCRIPTION" VARCHAR(1024),
    "DATA" LONG VARCHAR,
    "LAST_MODIF_TIME" TIMESTAMP,
    PRIMARY KEY (ID)
);
