/*
 * File:           FormatHandler.java
 * Date:           December 13, 2012  7:14 PM
 *
 * @author  washaofe
 * @version generated by NetBeans XML module
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lumens.model.serializer.parser;

import org.xml.sax.Attributes;
import org.xml.sax.SAXException;

/**
 *
 * @author shaofeng wang (shaofeng.cjpw@gmail.com)
 */
public interface FormatHandler {
    /**
     *
     * A container element start event handling method.
     *
     * @param meta attributes
     */
    public void start_format_list(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_format_list() throws SAXException;

    /**
     *
     * A data element event handling method.
     *
     * @param data value or null
     * @param meta attributes
     */
    public void handle_property(final String data, final Attributes meta) throws SAXException;

    /**
     *
     * A container element start event handling method.
     *
     * @param meta attributes
     */
    public void start_format(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_format() throws SAXException;
}
