/*
 * File:           TransformRuleHandlerImpl.java
 * Date:           December 10, 2014  7:09 PM
 *
 * @author  washaofe
 * @version generated by NetBeans XML module
 */
/*
 * Copyright Lumens Team, Inc. All Rights Reserved.
 */

package dtd;

import org.xml.sax.Attributes;
import org.xml.sax.SAXException;

/**
 *
 * @author Shaofeng Wang <shaofeng.wang@outlook.com>
 */
public class TransformRuleHandlerImpl implements TransformRuleHandler {
    public static final boolean DEBUG = false;

    public void start_transform_rule_item(final Attributes meta) throws SAXException {
        if (DEBUG)
            System.err.println("start_transform_rule_item: " + meta);
    }

    public void end_transform_rule_item() throws SAXException {
        if (DEBUG)
            System.err.println("end_transform_rule_item()");
    }

    public void start_transform_rule_list(final Attributes meta) throws SAXException {
        if (DEBUG)
            System.err.println("start_transform_rule_list: " + meta);
    }

    public void end_transform_rule_list() throws SAXException {
        if (DEBUG)
            System.err.println("end_transform_rule_list()");
    }

    public void handle_for_each(final String data, final Attributes meta) throws SAXException {
        if (DEBUG)
            System.err.println("handle_for_each: " + meta);
    }

    public void start_transform_rule(final Attributes meta) throws SAXException {
        if (DEBUG)
            System.err.println("start_transform_rule: " + meta);
    }

    public void end_transform_rule() throws SAXException {
        if (DEBUG)
            System.err.println("end_transform_rule()");
    }

    public void handle_script(final String data, final Attributes meta) throws SAXException {
        if (DEBUG)
            System.err.println("handle_script: " + meta);
    }

}
