--------------------------------------------------------
--  文件已创建 - 星期三-九月-04-2013   
--------------------------------------------------------
Insert into DICT_编制类别 (编制代码,编制类别) values ('10','教学类');
Insert into DICT_编制类别 (编制代码,编制类别) values ('11','教学');
Insert into DICT_编制类别 (编制代码,编制类别) values ('12','科研');
Insert into DICT_编制类别 (编制代码,编制类别) values ('13','教学兼行政');
Insert into DICT_编制类别 (编制代码,编制类别) values ('20','行政类');
Insert into DICT_编制类别 (编制代码,编制类别) values ('21','行政');
Insert into DICT_编制类别 (编制代码,编制类别) values ('22','政工');
Insert into DICT_编制类别 (编制代码,编制类别) values ('23','财会');
Insert into DICT_编制类别 (编制代码,编制类别) values ('24','档案');
Insert into DICT_编制类别 (编制代码,编制类别) values ('25','校刊');
Insert into DICT_编制类别 (编制代码,编制类别) values ('26','工程');
Insert into DICT_编制类别 (编制代码,编制类别) values ('27','行政兼教学');
Insert into DICT_编制类别 (编制代码,编制类别) values ('28','政工兼教学');
Insert into DICT_编制类别 (编制代码,编制类别) values ('30','教辅类');
Insert into DICT_编制类别 (编制代码,编制类别) values ('31','教辅类实验');
Insert into DICT_编制类别 (编制代码,编制类别) values ('32','图书');
Insert into DICT_编制类别 (编制代码,编制类别) values ('33','教辅类资料');
Insert into DICT_编制类别 (编制代码,编制类别) values ('34','实验兼教学');
Insert into DICT_编制类别 (编制代码,编制类别) values ('40','工人类');
Insert into DICT_编制类别 (编制代码,编制类别) values ('50','科研类');
Insert into DICT_编制类别 (编制代码,编制类别) values ('51','科研兼教学');
Insert into DICT_编制类别 (编制代码,编制类别) values ('52','科研类行政');
Insert into DICT_编制类别 (编制代码,编制类别) values ('53','科研类财会');
Insert into DICT_编制类别 (编制代码,编制类别) values ('54','科研类资料');
Insert into DICT_编制类别 (编制代码,编制类别) values ('55','实验');
Insert into DICT_编制类别 (编制代码,编制类别) values ('56','科研类工人');
Insert into DICT_编制类别 (编制代码,编制类别) values ('59','学报');
Insert into DICT_编制类别 (编制代码,编制类别) values ('60','校办企业类');
Insert into DICT_编制类别 (编制代码,编制类别) values ('61','校办企业工程、行政和财会');
Insert into DICT_编制类别 (编制代码,编制类别) values ('62','校办企业工人');
Insert into DICT_编制类别 (编制代码,编制类别) values ('63','校办企业其它');
Insert into DICT_编制类别 (编制代码,编制类别) values ('70','附设机构类');
Insert into DICT_编制类别 (编制代码,编制类别) values ('71','附设机构类行政');
Insert into DICT_编制类别 (编制代码,编制类别) values ('72','附设机构类工人');
Insert into DICT_编制类别 (编制代码,编制类别) values ('73','附设机构类其他');
Insert into DICT_编制类别 (编制代码,编制类别) values ('99','其他类');
